import json
from google.adk.agents import LlmAgent, SequentialAgent
from google.adk.tools import FunctionTool
from backend.services.supabase_client import supabase

from agents.reasoning.risk_analyst_agent import build_risk_analyst_agent
from agents.reasoning.hypothesis_agent import build_hypothesis_agent
from agents.reasoning.scoring_agent import build_scoring_agent

# Keep old imports available for backwards compatibility if needed
from agents.reasoning.cluster_agent import build_cluster_agent
from agents.reasoning.exposure_agent import build_exposure_agent

@FunctionTool
def save_risk_case(case_json: str) -> str:
    """Saves the final RiskCase JSON object to Supabase database."""
    try:
        case = json.loads(case_json)
        supabase.table("risk_cases").insert(case).execute()
        return json.dumps({"status": "success", "case_id": case.get("case_id")})
    except Exception as e:
        return json.dumps({"error": str(e)})

def build_reasoning_coordinator() -> SequentialAgent:
    # Merged: Risk Analyst Agent replaces the parallel Cluster + Exposure agents
    risk_analyst = build_risk_analyst_agent()
    hypothesis_agent = build_hypothesis_agent()
    scoring_agent = build_scoring_agent()

    # Persister saves the final RiskCase to DB
    persister = LlmAgent(
        name="persister_agent",
        description="Takes the RiskCase JSON and saves it to the database.",
        instruction="Take the structured RiskCase generated by the Scoring Agent and use `save_risk_case` to save it.",
        model="gemini-2.5-flash",
        tools=[save_risk_case]
    )

    # Sequential pipeline: RiskAnalyst → Hypothesis → Scoring → Persister
    pipeline = SequentialAgent(
        name="risk_reasoner_coordinator",
        description="Coordinates reasoning from raw events to a calculated RiskCase.",
        sub_agents=[risk_analyst, hypothesis_agent, scoring_agent, persister]
    )

    return pipeline
