import json
from google.adk.agents import LlmAgent, SequentialAgent, ParallelAgent
from google.adk.tools import FunctionTool
from backend.services.supabase_client import supabase

from agents.reasoning.cluster_agent import build_cluster_agent
from agents.reasoning.exposure_agent import build_exposure_agent
from agents.reasoning.hypothesis_agent import build_hypothesis_agent
from agents.reasoning.scoring_agent import build_scoring_agent

@FunctionTool
def save_risk_case(case_json: str) -> str:
    """Saves the final RiskCase JSON object to Supabase database."""
    try:
        case = json.loads(case_json)
        supabase.table("risk_cases").insert(case).execute()
        return json.dumps({"status": "success", "case_id": case.get("case_id")})
    except Exception as e:
        return json.dumps({"error": str(e)})

def build_reasoning_coordinator() -> SequentialAgent:
    cluster_agent = build_cluster_agent()
    exposure_agent = build_exposure_agent()
    hypothesis_agent = build_hypothesis_agent()
    scoring_agent = build_scoring_agent()
    
    # We define a coordinator that uses ADK transfer or directly handles sequential steps
    # The prompt actually specified: 
    # "Run ClusterAgent + ExposureAgent in parallel using ParallelAgent before handing off to HypothesisAgent then ScoringAgent sequentially."
    
    parallel_gathering = ParallelAgent(
        id="parallel_gathering_agent",
        name="Parallel Data Gathering",
        description="Runs Cluster and Exposure analysis together.",
        agents=[cluster_agent, exposure_agent]
    )
    
    # We use a final wrapper agent to call the save tool since SequentialAgent just runs subagents in order
    persister = LlmAgent(
        id="persister_agent",
        name="Risk Case Persister",
        description="Takes the RiskCase JSON and saves it to the database.",
        instructions="Take the structured RiskCase generated by the Scoring Agent and use `save_risk_case` to save it.",
        model="gemini-2.5-flash",
        tools=[save_risk_case]
    )
    
    pipeline = SequentialAgent(
        id="risk_reasoner_coordinator",
        name="Risk Reasoner Coordinator",
        description="Coordinates reasoning from raw events to a calculated RiskCase.",
        agents=[parallel_gathering, hypothesis_agent, scoring_agent, persister]
    )
    
    return pipeline
